import { Paper } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import FormLogin from "../components/FormLogin";
import HeaderLogin from "../components/Header/HeaderLogin";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LOGIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderLogin />
      <main className={styles.main}>
       <FormLogin/>
      </main>
    </div>
  );
}
